services:
  frontend:
    container_name: UzDuokFrontend-frontend
    build: 
      context: .
      dockerfile: ./docker/local/Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/var/www/html
    networks:
      - UzDuokFrontend-frontend
networks:
  UzDuokFrontend-frontend:
    name: UzDuokFrontend-network
    external: true