services:
  frontend:
    container_name: UzDuokFrontend-frontend
    build: 
      context: .
      dockerfile: ./docker/local/Dockerfile
    ports: 
      - "3000:5173"
    volumes:
      - .:/var/www/html
    networks:
      - UzDuokFrontend-frontend
networks:
  UzDuokFrontend-frontend:
    name: UzDuokBackend-network
    external: true